# Generated by Django 4.0.5 on 2022-09-03 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacansii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('Администратор', 'Администратор'), ('Официант', 'Официант'), ('Бармен', 'Бармен'), ('Уборщица', 'Уборщица'), ('Посудамойщица', 'Посудамойщица'), ('Повар', 'Повар'), ('Шеф-повар', 'Шеф-повар'), ('Хостес', 'Хостес')], max_length=100, null=True, verbose_name='Должность')),
                ('requirement', models.CharField(max_length=150, null=True, verbose_name='Требования')),
                ('responsibilities', models.CharField(max_length=300, null=True, verbose_name='Обязанности')),
                ('terms', models.CharField(max_length=150, null=True, verbose_name='Условия')),
                ('income', models.CharField(max_length=150, null=True, verbose_name='Доход')),
                ('city', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Чуй', 'Чуй'), ('Нарын', 'Нарын'), ('Ысык-Кол', 'Ысык-Кол'), ('Баткен', 'Баткен'), ('Талас', 'Талас'), ('Ош', 'Ош'), ('Другой город', 'Другой город')], max_length=150, null=True, verbose_name='Город')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Создать ваканцию',
            },
        ),
    ]
