# Generated by Django 4.0.5 on 2022-09-03 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vakansii', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacansii',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='vacansii',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
