# Generated by Django 4.0.5 on 2022-09-03 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vakansii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otclik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otclik', to=settings.AUTH_USER_MODEL)),
                ('vakansii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otclik', to='vakansii.vacansii')),
            ],
        ),
    ]
